services:
  valheim:
    build: .
    ports:
      - "2456-2457:2456-2457/udp"
      - "3030:3030/tcp"
    volumes:
      - valheim-server:/server
    environment:
      SERVER_NAME: ${SERVER_NAME:-My Valheim Server}
      WORLD_NAME: ${WORLD_NAME:-Dedicated}
      PORT: ${PORT:-2456}
      PASSWORD: ${PASSWORD}
      PUBLIC: ${PUBLIC:-false}
      CROSSPLAY: ${CROSSPLAY:-true}
    restart: unless-stopped
    stop_grace_period: 60s

volumes:
  valheim-server:
